GET http://localhost:5000/login

###



POST http://localhost:5000/login
Content-Type: "application/json"

{
    "id":"123",
    "name":"123",
}

###


GET http://localhost:5000/signup

###


POST http://localhost:5000/signup
Content-Type: "application/json"

{
    "id":"1234",
    "name":"1234",
    "email":"1234@yahoo.com",
    "password":"sw4234324swadwasd",
    "collage":"IT",
    "phone":"21237986"
}

###

GET http://localhost:5000/users

